<a href="https://colab.research.google.com/github/Noslen45/base_Iris/blob/main/agrupamento_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px # criação de gráficos dinâmicos
import plotly.graph_objects as go # criação e cocatenização de gráficos
from sklearn.preprocessing import StandardScaler # Para realizar a padronização dos dados
from sklearn.cluster import KMeans

In [ ]:
#Abrindo o arquivo de dados
base_iris = pd.read_csv('base_iris.csv', sep = ';')


In [ ]:
# Ver como estão os dados
base_iris.head()
# são dados dos tamanhos das pétalas

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
base_iris.shape
#150 linhas com 5 colunas na tabela acima

(150, 5)

In [ ]:
#verifica as classes das flores
base_iris['Class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# Realizando agrupamento das pétalas

In [ ]:
#olhando na tabela, posso ver que estão nas colunas 2 e 3
#crio variavel x com as colunas petal length e petal width
x_petala = base_iris.iloc[:,[2,3]].values
#iloc = todos os registros
x_petala[:10] #limitando até 10 registros

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

# Normalizando os dados
como os dados estão em escala muito diferentes,preciso padronizar para que uns dados não sejam considerados mais importantes do que outros

In [ ]:
normalizar_dados = StandardScaler()
x_petala = normalizar_dados.fit_transform(x_petala)
x_petala[:10]

array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

Calculo do cluster
# usando o metodo do cotovelo, que é a soma da distancia quadrada de cada ponto e o centroide do cluster (wcss)

In [ ]:
wcss_petala = [] #criando uma lista vazia
for i in range(1, 11):
  kmeans_petala = KMeans(n_clusters=i, random_state=0)#Executa o kmeans para todos os clusters e random_state=0 para fixar e obter os mesmos resutlados
  kmeans_petala.fit(x_petala)#realiza o treinamento
  wcss_petala.append(kmeans_petala.inertia_)

In [ ]:
#visualizando os valores de wcss
for i in range(len(wcss_petala)):
  print('Cluster', i+1, 'Valor do wcss', wcss_petala[i])

Cluster 1 Valor do wcss 300.0000000000001
Cluster 2 Valor do wcss 54.14584701344988
Cluster 3 Valor do wcss 18.046983891906276
Cluster 4 Valor do wcss 12.307440251261843
Cluster 5 Valor do wcss 9.181131495513899
Cluster 6 Valor do wcss 7.215096212730807
Cluster 7 Valor do wcss 6.026593155951448
Cluster 8 Valor do wcss 5.173315218915379
Cluster 9 Valor do wcss 4.423975871969686
Cluster 10 Valor do wcss 3.9139417830543204


# Criando gráfico

In [ ]:
grafico_cotovelo_petala = px.line(x=range(1, 11), y=wcss_petala)
grafico_cotovelo_petala.show()

In [ ]:
kmeans_petala = KMeans(n_clusters=3, random_state=0)
label_cluster_petala = kmeans_petala.fit_predict(x_petala)

In [ ]:
#verifica a classificação dos clusters
label_cluster_petala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
centroides_petala=kmeans_petala.cluster_centers_
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

# Grafico de agrupamentos das caracteristicas do tamanho e comprimento das petalas

In [ ]:
grafico_petala = px.scatter(x = x_petala[:,0], y = x_petala[:,1], color= label_cluster_petala)
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y = centroides_petala[:,1], size = [7,7,7])
grafico_final_petala = go.Figure(data = grafico_petala.data + grafico_centroide_petala.data)
grafico_final_petala.show()

### Realizando o agrupamento com dados da sépala

In [ ]:
x_sepala = base_iris.iloc[:,[0,1]].values
x_sepala[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [ ]:
wcss_sepala = []
for i in range(1,11):
  kmeans_sepala = KMeans(n_clusters=i, random_state=0)
  kmeans_sepala.fit(x_sepala)
  wcss_sepala.append(kmeans_sepala.inertia_)

In [ ]:
for i in range(len(wcss_sepala)):
  print('Cluster', i+1, 'Valor do WCSS', wcss_sepala[i])

Cluster 1 Valor do WCSS 130.18093333333337
Cluster 2 Valor do WCSS 57.98240604207879
Cluster 3 Valor do WCSS 37.12370212765957
Cluster 4 Valor do WCSS 27.98254281735862
Cluster 5 Valor do WCSS 20.971913367009606
Cluster 6 Valor do WCSS 17.238695238095236
Cluster 7 Valor do WCSS 14.631909607059608
Cluster 8 Valor do WCSS 12.911711915446565
Cluster 9 Valor do WCSS 11.059663725936947
Cluster 10 Valor do WCSS 9.449454365079365


# Grafico cotovelo sepala

In [ ]:
grafico_cotovelo_sepala = px.line(x=range(1,11), y=wcss_sepala)
grafico_cotovelo_sepala.show()

In [ ]:
kmeans_sepala = KMeans(n_clusters=3, random_state=0)
label_cluster_sepala = kmeans_sepala.fit_predict(x_sepala)

In [ ]:
label_cluster_sepala

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [ ]:
centroides_sepala=kmeans_sepala.cluster_centers_
centroides_sepala

array([[5.77358491, 2.69245283],
       [5.006     , 3.418     ],
       [6.81276596, 3.07446809]])

# GRAFICO AGRUPAMENTO SEPALA

In [ ]:
grafico_sepala = px.scatter(x = x_sepala[:,0], y = x_sepala[:,1], color= label_cluster_sepala)
grafico_centroide_sepala = px.scatter(x = centroides_sepala[:,0], y = centroides_sepala[:,1], size = [7,7,7])
grafico_final_sepala = go.Figure(data = grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final_sepala.show()